version: "3.9"

services:
  pinehaus-frontend-staging:
    build:
      context: ../frontend
      dockerfile: Dockerfile
    image: pinehaus-frontend-staging:1.0.0
    container_name: pinehaus-frontend-staging
    restart: always
    ports:
      - "5500:3000"
    networks:
      - pinehaus_network

networks:
  pinehaus_network:
    driver: bridge
    external: true
