server:
  servlet:
    context-path: /api

logging:
  level:
    net:
      pinehaus:
        backend: TRACE

app:
  jwtExpirationInMs: ${JWT_EXPIRATION_IN_MS}
  jwtSecret: ${JWT_SECRET}
  google:
    client-id: ${GOOGLE_CLIENT_ID}

spring:
  datasource:
    url: ${BACKEND_DATASOURCE_URL}
    username: ${BACKEND_DATASOURCE_USERNAME}
    password: ${BACKEND_DATASOURCE_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true