name: "@pinehaus/frontend Workflow"

on:
  push:
    branches: [master]
    paths:
      - "frontend/**"

  pull_request:
    branches: [master]
    paths:
      - "frontend/**"

jobs:
  build:
    name: Build @pinehaus/frontend
    runs-on: [self-hosted]

    steps:
      - uses: actions/checkout@v3
      - uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - name: Install dependencies
        working-directory: frontend
        run: bun install

      - name: Build
        working-directory: frontend
        run: bun run build

  docker-image:
    name: Build @pinehaus/frontend docker image
    needs: build
    runs-on: [self-hosted]

    steps:
      - uses: actions/checkout@v3

      - name: Build docker image
        run: docker compose -f docker/docker-compose.yml build

      - name: Run docker image
        run: docker compose -f docker/docker-compose.yml restart
